// TDD Phase 2: Quick Store Tool (GREEN phase implementation)
// Author: PB and Claude
// Date: 2025-07-04

import { BaseMCPTool, MCPResponse } from './base-tool.js';
import { MemoryType, MemoryProvenance, StoreMemoryOutcome } from '../db/service.js';
import { formatHashForDisplay } from '../utils/hash.js';

export interface QuickStoreParams {
  content: string;
  type?: 'conversation' | 'code' | 'decision' | 'reference';
  status?: string;
  tags?: string[];
  source_key?: string;
  provenance?: MemoryProvenance;
  // Consolidation reverse edge (claude-mem#12): the sibling memory_ids this
  // memory was synthesized from, written at synthesis time. Shape-validated
  // at the route; existence of the ids is the verb-side evidence gate's job
  // (same stance as evict_reason free TEXT).
  consolidated_from?: string[];
}

export class QuickStoreTool extends BaseMCPTool<QuickStoreParams> {
  constructor(
    dbService: any,
    private storeMemoryWithTagsFunction: (content: string, type: MemoryType, metadata: any, tags?: string[], sourceKey?: string, provenance?: MemoryProvenance) => Promise<StoreMemoryOutcome>,
    private detectMemoryTypeFunction: (content: string) => MemoryType,
    private generateSmartTagsFunction: (content: string, type: MemoryType) => Promise<string[]>
  ) {
    super(dbService);
  }

  async handle(params: QuickStoreParams): Promise<MCPResponse> {
    try {
      const { content, type, status, tags = [], source_key, provenance, consolidated_from } = params;
      
      // Auto-detect memory type if not provided
      const detectedType = type || this.detectMemoryTypeFunction(content);
      
      // Generate smart tags
      const autoTags = await this.generateSmartTagsFunction(content, detectedType);
      
      // Combine auto-generated tags with user-provided ones
      const allTags = [...new Set([...autoTags, ...tags])];
      
      // Extract key decisions if this appears to be a decision
      let keyDecisions: string[] | undefined;
      if (detectedType === 'decision') {
        const decisionMatches = content.match(/(?:decided|chose|selected|picked|opted)\s+[^.!?]*[.!?]/gi);
        keyDecisions = decisionMatches?.map(d => d.trim()) || undefined;
      }
      
      // Use shared storage function
      const outcome = await this.storeMemoryWithTagsFunction(content, detectedType, {
        implementation_status: status,
        key_decisions: keyDecisions,
        date: new Date().toISOString(),
        ...(consolidated_from?.length ? { consolidated_from } : {})
      }, allTags, source_key, provenance);

      return {
        content: [{
          type: 'text',
          text: JSON.stringify({
            success: true,
            memoryId: formatHashForDisplay(outcome.memoryId),
            detectedType: detectedType,
            autoDetected: !type,
            tags: allTags,
            autoGeneratedTags: autoTags.length,
            keyDecisions: keyDecisions,
            // Echoes the ACCEPTED INPUT, not a read-back of the row — on an
            // upsert conflict the COALESCE policy can keep earlier values
            // this echo doesn't see. Persistence assertions need a DB read.
            // Conformance v1.2.0 pins the echo at TOP LEVEL (session_id/
            // host/agent_id); the nested object stays for back-compat.
            provenance: provenance,
            ...(provenance ?? {}),
            // consolidated_from is echoed only when the write went through
            // (outcome.updated): on the W8 refusal paths below nothing is
            // written, and a consolidation verb acts destructively (evicts
            // siblings) on this echo — it must not claim an edge that was
            // never stored. Caveat: an UNKEYED content-hash dedup against a
            // live row reports updated:true without writing metadata, and is
            // indistinguishable here; callers doing destructive follow-ups
            // must read the row back (GET /memory/:id) before acting.
            ...(consolidated_from?.length && outcome.updated ? { consolidated_from } : {}),
            // W8 signals (present only when meaningful): evicted = sticky-
            // tombstone collision; updated:false + deferred_to = keyed
            // no-clobber refusal. Either also means tags were NOT attached.
            ...(outcome.evicted ? { evicted: true } : {}),
            ...(outcome.updated ? {} : { updated: false, deferred_to: outcome.deferred_to ?? null })
          }, null, 2)
        }]
      };
    } catch (error) {
      return this.handleError(error, 'quick-store');
    }
  }
}